### ISSUE TITLE
feature: support defaults for related resource references

### ISSUE THREAD

**Issue by embik** [kcp-dev/api-syncagent#25]
### Feature Description

Some tools (e.g. external-secrets-operator) might silently default related resource references. In those cases, the given path of a related resource is empty, but we still want to sync a generated object.

Because of that, we should support another "default" field in related resources. This field should support some common patterns (e.g. matching the parent object name) to construct the implied default object names and sync them.

### Proposed Solution

The API should look something like this:

```yaml
# configure where in the parent object we can find
# the name/namespace of the related resource (the child)
reference:
    name:
        path: spec.secretName
    default: "$resourceName"
```

If the given path cannot be found, syncagent should look for a related resource under the "default" name and consider that to be the referenced object.

### Want to contribute?

- [ ] I would like to work on this issue.
