### ISSUE TITLE
bug: sync-related labels are not stripped from related objects

### ISSUE THREAD

**Issue by xrstf** [kcp-dev/api-syncagent#35]
### Describe the bug

I created something with the api-syncagent and it synced back a Secret (from the service cluster into kcp). In kcp however I could see that the object still has its sync labels:

```yaml
apiVersion: v1
data: ...
kind: Secret
metadata:
  annotations:
    kcp.io/cluster: h7rup33istfoi4ya
  creationTimestamp: "2025-03-04T16:56:34Z"
  labels:
    claimed.internal.apis.kcp.io/3nVgigiuGzWStDU5fm7mHXM79pfJ9OFQpZYIlh: fytMX0tJGZ2OALpkwPYShJbMCNKFJxPZyau1s
    syncagent.kcp.io/remote-object-cluster: ""
    syncagent.kcp.io/remote-object-name: test-connection-details
    syncagent.kcp.io/remote-object-namespace: org-h7rup33istfoi4ya-7505d64a54e061b7acd5
  name: test-connection-details
  namespace: default
type: connection.crossplane.io/v1alpha1
```

### Steps To Reproduce

Configure the agent to have a related Secret that originates on the service cluster.

### Expected Behaviour

All sync-related metadata should be kept on the service cluster only.
